---
Name: contentblocks
---
ContentBlock:
    include_bootstrap: false
ContentBlock_ColumnLayout:
  column_classes:
    - 'content-block__column'
  row_classes:
    - 'content-block__row'
ContentBlock_Accordion:
  accordion_classes:
    - 'content-block__accordion'
ContentBlock_TileSection:
  tile_classes:
    - 'content-block__tile'
  tile_templates:
    ContentTile_Basic: 'Default'
