---
Name: contentblocks
---
ContentBlock:
    include_bootstrap: false
    types:
      ContentBlock_TileSection: 'Tile Section'
      ContentBlock_ColumnLayout: 'Column Layout'
      ContentBlock_Accordion: 'Accordion'
ContentBlock_TileSection:
  tile_templates:
    ContentTile_Basic: 'Default'
